### ISSUE TITLE
Exclude labels filter

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#1]
Imported from https://bitbucket.org/mbari/gridview/issues/4/exclude-labels-filter
---
When starting gridview, it might be helpful to have a way of excluding already adjusted boxes (akin to the “Hide Labeled” button in the GUI). I think having that capability might prevent some redundant downloading if a user is splitting a big concept over multiple labeling sessions.

**Comment by NancyJS** [comment]
VL: annotation staff may not need this feature, could be bumped down to next version. Also, does this overlap w/ #55?

**Comment by kevinsbarnard** [comment]
@NancyJS Got it. This is distinct from the #55 as this issue is filtering prior to the VARS query, whereas the others are simply filtering the localizations in the view.

**Comment by kevinsbarnard** [comment]
Implemented in v0.10.0
