### ISSUE TITLE
Delete observations with localizations

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#12]
From @lonnylundsten 2/8/2023:
> We have a problem in the way vars-gridview deals with these new localizations in vars. Over the last couple of days I have deleted hundreds of bad localizations from gridview, assuming that the annotations for those were also being deleted. However, when I open vars, I see that those annotations did not get deleted although their localizations did. My current solution will be to sort by existence of localization in vars (fg/s column) and delete the annotations that no longer have localizations. I guess we didn't really think about the behind the scenes behavior of gridview, but for this particular workflow, I think deletion of a localization in gridview must also delete the localizations in vars. Thoughts?

We need to add logic to vars-gridview in order to (optionally) delete an annotation when its localization is deleted. Due to the 1:N nature of observation:associations, there may be multiple bounding linked tied to a single observation. We need to be careful about how this is handled.

Proposal:
1. User deletes a set of localizations
2. For each localization, vars-gridview deletes the corresponding bounding box association in VARS
3. For each parent observation of the bounding box association, vars-gridview checks if it is "dangling" (i.e., no more linked bounding box associations)
4. Non-dangling observations (i.e., ones with more bounding boxes) are ignored
5. The list of dangling observations will be presented to the user to confirm deletion; if accepted, those observations are deleted from VARS

**Comment by hohonuuli** [comment]
Can we add an undo button too? In case users accidentally delete things they didn't want to?

**Comment by kevinsbarnard** [comment]
All things are possible in software... I'll add it to the list.

**Comment by kevinsbarnard** [comment]
This functionality is complete, minus the undo button. The undo button will be covered in #13
