### ISSUE TITLE
Grab frame for localizations without corresponding image.

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/vars-gridview#14]
From Kris on Slack:

> Hello Kevin and Brian, I've been making a number of new localizations in D0858, yesterday tried to view them in Gridview and they aren't loading there. Most of them were made from the mov files so no web video available, makes sense. We'll want to instate a system for grabbing those from corresponding mp4 files before our next model training since midwater team uses mov files exclusively (until we get to 4K video then we'll annotate from  the mezzanine files).
I tested making a few localizations using the D0858 mp4 files instead, with and without corresponding framegrabs, and still not able to see my localizations in gridview. Lonny tried merging the dive and I waited until this morning in case some merge or load needs to happen overnight but still not viewable. The only localizations available to view in Gridview for this dive are ones made in past on the real-time framegrabs. My new localizations would have observer kwalz and concepts are appendicularia and caecosagitta macrocephala. On mov files concept is doliolina, I can test more in the next few days or early next week. Thanks for any feedback!

> [11:06](https://mbari.slack.com/archives/C027ZDPKHE1/p1677092774918189)
*Correction, there is a web video available for these files but the mov file is put to tape and not recalled, so that is why I receive the "no web video available" message in terminal.

**Comment by kevinsbarnard** [comment]
Fixed in [v0.2.3](https://github.com/mbari-org/vars-gridview/releases/tag/v0.2.3)
