### ISSUE TITLE
additions to gridview

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#2]
Imported from https://bitbucket.org/mbari/gridview/issues/8/additions-to-gridview
---
I’m requesting a few new features for gridview now that we will be using it as a first cut for cleaning ml proposals that are being used in production.

1. I would like to be able to drag-select (draw a box) to select localizations in the grid: https://www.computerhope.com/jargon/d/dragsele.htm

2. Now that we’ll be looking at a lot of different classes in the grid, I would like those classes to be differentiated within the grid using different color behind the class label: https://ozzmaker.com/add-colour-to-text-in-python/

3. When right-clicking, I would like to see a context-menu that allows me to do things like delete localization(s) and/or edit a class label.

4. Change the font sizes to bold and about 2 points larger, they are too small to see clearly (or make this a user adjustable option).

5. Intergrate with Brian’s m3-support code, which opens a video file in sharktopoda 2 for visualizing localizations on video. Ideally when selecting a localization in the grid, sharktopoda would navigate to that frame. Being able to edit localizations in sharktopoda would be great too. Also we would need a toggle switch to quickly turn on/off the localization because sometimes its hard to see under the lines of the box.

6. add the ability to add the ‘maybe’ association

7. This is a maybe, if possible – for duplicate observations add the ability to add identity ref number to those

The idea behind these is to speed up the process of cleaning localizations. It may not seem like a big deal but when changing lots of class labels, the current method of selecting and changing them is slow and cumbersome. It would be nice to add more modern GUI touches to the workflow.

**Comment by kevinsbarnard** [comment]
@lonnylundsten I'm moving these feature requests here, as this is the official repository for vars-gridview.

**Comment by lonnylundsten** [comment]
Thanks, Kevin. I should have put them here...I couldn't remember if we were on GitHub or bitbucket now.

**Comment by kevinsbarnard** [comment]
No worries! I mainly moved it here to give separation between the file-based gridview and the VARS integration, so it's not just living in a separate branch.

**Comment by kevinsbarnard** [comment]
This issue has been split into separate constituent issues, so I'm closing this one.
