### ISSUE TITLE
Add experimental visual similarity, duplicate feature 

### ISSUE THREAD

**Issue by danellecline** [mbari-org/vars-gridview#20]
@kevinsbarnard ; Lonny requested that I work on this feature, primarily some reuse from my python code for the UAV and BioDiversity projects. With your guidance, I'd like to create a branch to work on this.

This feature would 

* Use similarity based on cosine distance from features from a model; likely a vision transformer model (we are working on training a few of them, primarily architectures that do not need a lot of data and input small image sizes) 
* Provide the results in a sortable way, much like you do with other features, e.g. color
* Flag duplicates based on high similarity

**Comment by danellecline** [comment]
Thank you @kevinsbarnard  for the walk-through today. That was helpful!

**Comment by NancyJS** [comment]
@danellecline can you provide a status update on this? It would be great to move this one up in priority to 2023.

**Comment by lonnylundsten** [comment]
@kevinsbarnard perhaps use clustimage (https://github.com/erdogant/clustimage) or some other image similarity app to implement this relatively quickly?

**Comment by danellecline** [comment]
I'm going to close this issue now, assuming it has been addressed by Kevin.

**Comment by kevinsbarnard** [comment]
Notes for posterity:
- In VARS GridView v0.12.0, the ability was added to extract ROI features (embeddings) and perform a similarity sort on the ROIs in the grid.
  - Features are computed
    1. as the images are downloaded
    2. whenever the ROI bounds are changed/the image is updated
  - Features are cached within the ROI data structure to facilitate quick comparison
  - [Cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity) is used to compare ROIs by their feature vectors; this is performed on the CPU
  - v0.12.1 added a lookup of available PyTorch backends to support non-CUDA acceleration of feature extraction
- Currently, a single feature extractor is supported: [dreamsim](https://github.com/ssundaram21/dreamsim).
- An abstraction was used to support extension to other feature extractors down the road. The UI is not yet implemented to switch between different feature extractors; this would need to be added.
