### ISSUE TITLE
Observer is different after adjusting localization

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-org/vars-gridview#37]
When a person adjusts the box in gridview, the observer changes and then appears as if it may have been validated when in fact that was not the intention. Issue discussed in early June meeting with Kevin.

Observer name should change only when validating or changing the class label.

Hoping to have completed by 11/30/2023.

**Comment by kevinsbarnard** [comment]
@lonnylundsten I made an issue for this (#19) when we discussed this behavior before, and closed it after concluding that the observation's observer does not change when the box is modified or verified -- except in the case when the label is changed. I'm wondering if we're conflating terms ("observer" is overloaded between the observation and the bounding box).

For this issue, do you mean the observer in the bounding box JSON, or the observer in the observation (annotation)?

For context, a long time ago when we first designed vars-localize and vars-gridview, we made these distinctions:

1. Observation "observer": who created the annotation or who last updated its concept
2. Bounding box "observer": who created the bounding box or last updated its dimensions
3. Bounding box "verifier": who last verified the bounding box dimensions as accurate

In my last testing of gridview per #19, I checked that changes to these values are made only as follows:

1. User verifies a bounding box as-is (empty concept/part boxes) --> both observers are unmodified, verifier is updated
2. User resizes/moves a bounding box --> observation observer is unmodified, bounding box observer is updated, verifier is unmodified
3. User renames a bounding box's observation --> observation observer is updated, bounding box observer is unmodified, verifier is updated

Do we want to change that? If not, are you noticing something other than that happening?

**Comment by lonnylundsten** [comment]
This issue is being reported by Kris and Larissa. I will ask them to verify and determine it is/is not working as expected. If its A-OK, I'll close this issue.

**Comment by kevinsbarnard** [comment]
Thanks @lonnylundsten for testing! It sounds like gridview is in fact doing what's described above, but we may need to sync on how we want to name these fields or define the logic behind how they're populated/updated. I'll close this issue but we can open new ones if we want to make any changes.
