### ISSUE TITLE
Bring video windows top-level on open

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#42]
From Kyra:

> Can we brainstorm on a way we can get the video window not to pop up right underneath the Gridview window? I am doing a lot of window shuffling around, especially with the SD files.

This may be possible using the `show` command in Sharktopoda 2. Otherwise, this may be tricky.

**Comment by kevinsbarnard** [comment]
Implemented in v0.8.0. A Sharktopoda 2 `show` command is sent when a localization is shown.

**Comment by KSchlining** [comment]
Currently using v0.8.0 and it doesn't look like this is fixed.

**Comment by kevinsbarnard** [comment]
@KSchlining Roger that. We have a command in Sharktpoda 2 (`show`) that's intended to bring a given video window top-level, and gridview is now sending that command to S2 as of v0.8.0. So, this may need a change in how the `show` command is handled within S2.

@hohonuuli Do you know if the `show` command will bring the focus to the S2 application within macOS, or does it just reorder its windows internally?

**Comment by hohonuuli** [comment]
Show should be bringing the given window the front but it does __not__ change the focused application.

**Comment by kevinsbarnard** [comment]
In v0.8.1, the `open -a` command is run for app `Sharktopoda` in order to bring it to the forefront.
