### ISSUE TITLE
Package VARS GridView

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#50]
It would be nice to have VARS GridView available as a standalone application. Potential solution: [fman build system](https://build-system.fman.io/)

**Comment by hohonuuli** [comment]
@kevinsbarnard It's likely you'll need to do code signing. If needed, contact Joe Gomez about getting added to MBARI's Apple Development team so you can get a signing certificate. See also <https://developer.apple.com/developer-id/>

**Comment by kevinsbarnard** [comment]
Moving forward with [PyInstaller](https://pyinstaller.org/en/stable/index.html). Currently setting up application build spec with relevant metadata.

So far, I've been able to get gridview built as either a single-file and single-folder windowed app on Linux and macOS. Looking into code signing and packaging into a DMG.

**Comment by kevinsbarnard** [comment]
Resource for multi-OS PyInstaller build a la GitHub Action: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions/

**Comment by kevinsbarnard** [comment]
Relevant gist for macOS code signing: https://gist.github.com/txoof/0636835d3cc65245c6288b2374799c43

**Comment by kevinsbarnard** [comment]
Awaiting addition to Apple development team from Joe

**Comment by kevinsbarnard** [comment]
Added; I've generated a Developer ID Application signing certificate for this. Now experimenting with [code signing via PyInstaller](https://pyinstaller.org/en/stable/feature-notes.html#macos-binary-code-signing) and testing on M1 Mac mini.

@hohonuuli I need to pick a bundle identifier for VARS GridView; I see that you're using `org.mbari.vars.ui` for VARS Annotation, so following from that, do you think `org.mbari.vars.gridview` is alright?

**Comment by hohonuuli** [comment]
>  do you think org.mbari.vars.gridview is alright?

👍🏻 That's a good choice

**Comment by kevinsbarnard** [comment]
I added a first bundled and signed (though not yet notarized) version of VARS GridView in [v0.8.1](https://github.com/mbari-org/vars-gridview/releases/tag/v0.8.1). I'll set up notarization next, but looks like it's working!

**Comment by hohonuuli** [comment]
Just in case you need this, here's the steps for notarizing Mondrian:

```sh
export MAC_CODE_SIGNER="Developer ID Application: Monterey Bay Aquarium Research Institute (<our id>)"

cd mondrian

# Java build stuff
./gradlew clean jpackage --info

cd mondrian/build/jpackage/

# Zipped app is easy to notarize
ditto -c -k --keepParent "Mondrian.app" "Mondrian.zip"

# Do the notarize thing
xcrun notarytool submit "Mondrian.zip" \
    --wait \
    --team-id <our id> \
    --apple-id brian@mbari.org \
    --password "xxxxxxx"

# State the notarization onto the app
xcrun stapler staple "Mondrian.app"

rm "Mondrian.zip"

# Repacked
ditto -c -k --keepParent "Mondrian.app" "Mondrian-$(git describe --tags).zip"
```

**Comment by kevinsbarnard** [comment]
Thanks @hohonuuli! That reference worked great; I just set up a [script](https://github.com/mbari-org/vars-gridview/blob/151f8b92c536e5d7c7be5d71cb1aa6673d8c1a30/build_macos.sh) to invoke the PyInstaller build (which performs deep code signing properly) and run the notarization + stapling. All seems to be working.
