### ISSUE TITLE
The image set "atolla" is not loading into Gridview, see terminal message below

### ISSUE THREAD

**Issue by kwalz** [mbari-org/vars-gridview#56]
I'm not able to load the "atolla" image set, all other sets have been loading fine so far. There could be an image or something corrupted in the set?... receive this message in terminal after it starts the downloading images task bar (it seems to make progress for some time but reaches an image that there is an issue):

Traceback (most recent call last):
  File "/Users/kwalz/miniconda3/lib/python3.10/site-packages/vars_gridview/scripts/run.py", line 395, in _do_query
    self.image_mosaic.sort_rect_widgets(default_sort_method)
  File "/Users/kwalz/miniconda3/lib/python3.10/site-packages/vars_gridview/lib/image_mosaic.py", line 471, in sort_rect_widgets
    sort_method.sort(self._rect_widgets)
  File "/Users/kwalz/miniconda3/lib/python3.10/site-packages/vars_gridview/lib/sort_methods.py", line 30, in sort
    rect_widgets.sort(key=cls.key, **kwargs)
  File "/Users/kwalz/miniconda3/lib/python3.10/site-packages/vars_gridview/lib/sort_methods.py", line 64, in key
    return rect.annotation_datetime() or datetime.min
  File "/Users/kwalz/miniconda3/lib/python3.10/site-packages/vars_gridview/lib/widgets.py", line 150, in annotation_datetime
    video_start_datetime = self.video_data["video_start_timestamp"]
KeyError: 'video_start_timestamp'

**Comment by kevinsbarnard** [comment]
@kwalz it looks like this is due to a video in VARS with a missing start timestamp. Gridview needs this value to compute the exact timestamp of the annotation, so it's throwing an error when it can't find it. The ideal solution for this would be to add the start timestamp to the video in VARS, but in any case, gridview should: warn about this, skip loading that particular annotation, and then continue loading the other valid annotations. I'll work on this now.

**Comment by kwalz** [comment]
Also true for Bathocyroe and Bolinopsis searches so seems to be widespread how many tapes may be missing start times. I'll see if Brian can get me a list of those tapes but unfortuntately it's not an easy fix to get tape parameters edited in vars db...

**Comment by kevinsbarnard** [comment]
This is fixed as of v0.4.5. Now, imaged moments that don't have a valid video will be skipped, and a WARNING will appear in the terminal during the query result parsing stage.

**Comment by kevinsbarnard** [comment]
@kwalz Let me know if that did the trick!

**Comment by kwalz** [comment]
Thanks, Kevin. I didn't see these messages until now so I am testing this issue this morning with the new version.

**Comment by kevinsbarnard** [comment]
Great to hear! Thanks for testing @kwalz.
