### ISSUE TITLE
Arrow through the grid

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-org/vars-gridview#58]
I would like the ability to arrow through the grid, such the using arrows up-down-left-right I can select different ROI's within the grid. This will be particularly useful when trying to find duplicates where mousing and clicking quickly becomes tedious and time consuming.

**Comment by kevinsbarnard** [comment]
Can do 👍🏼

**Comment by kevinsbarnard** [comment]
@lonnylundsten Implemented in v0.4.8. Click (get focus) somewhere in the grid view, then up/down/left/right keys will change the selection. If you have several localizations selected, the selection will be updated relative to the first selected localization.
