### ISSUE TITLE
Wishlist for next version: maintain sort selections for re-sorting

### ISSUE THREAD

**Issue by kwalz** [mbari-org/vars-gridview#65]
Not a priority, would be for next version. It would be nice to maintain sort selections for an image set until it is closed. So if I sort by label, depth, and then recorded timestamp and then clean up localizations, would be nice to re-sort with same parameters that I used without having to reselect those in same order again ...not sure if this is possible:)

**Comment by kevinsbarnard** [comment]
Got it, I think this is captured in #49.

**Comment by kevinsbarnard** [comment]
Implemented in v0.9.0
