### ISSUE TITLE
Minor: have cursor attention in username field on login window when Gridview starting up

### ISSUE THREAD

**Issue by kwalz** [mbari-org/vars-gridview#70]
This could be saved for next upgraded version of Gridview :). Would be quicker startup for user if the cursor was automatically in the login username window when Gridvew starts up.

**Comment by kevinsbarnard** [comment]
An update in the underlying GUI library (Qt) recently caused this, so I wrote a fix for this last week that restores the old behavior. It'll be rolled out in the next version of GridView!
