### ISSUE TITLE
GV hanging

### ISSUE THREAD

**Issue by KSchlining** [mbari-org/vars-gridview#71]
When I run a query I'm getting the spinning rainbow wheel of death and GV is hanging. I was using the concept 'animalia' as a test since it is a small/quick query. It was working fine for a query I did earlier this morning and the only thing I changed is that I cleared my cache then upped it from 1000 MB to 20000 MB. Maybe that is the problem?

**Comment by kwalz** [comment]
It's working for me now.
kris

**Comment by hohonuuli** [comment]
@kevinsbarnard Just a note that beholder was well and thouroughly stuck. Running `docker stop` and `docker kill` did nothing. I had to restart the docker daemon to unhang things.

**Comment by kevinsbarnard** [comment]
My sense is that this was a temporary issue with the database; I'll close this issue for now. I tested on both perseus and fog and all seems to be working.
