### ISSUE TITLE
sort grid by ROI sharpness

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-org/vars-gridview#80]
I was hoping we could look into adding image sharpness as a sorting method within the grid, possibly using something like the laplacian method (common method for assessing sharpness in an image).

 -- see attached screen grab.

<img width="650" alt="Screenshot 2024-10-02 at 12 38 38 PM" src="https://github.com/user-attachments/assets/f904e229-7b0b-4372-a6fd-6394ca247f0f">

**Comment by kevinsbarnard** [comment]
This was a quick one, so I went ahead and implemented it. This is released in vars-gridview v0.13.0.
